:toc:

# What's New in Spring Boot 2.6

Demo code from the webinar "What's New in Spring Boot 2.6" with some commentary and extra detail on the main points.

Also see:

* https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes[Release Notes] 
* https://github.com/spring-projects/spring-boot/milestones[Release schedule] on Github
* https://spring.io/projects/spring-boot#support[Support timelines] and https://github.com/spring-projects/spring-boot/milestones[Milestones on Github].

## Health Endpoints on Main Port

When the actuator endpoints are configured on a different port (`management.server.port`) the health groups `/health/liveness` and `/health/readiness` can give misleading status unless they are switched to the main `server.port`. If you set

```
management.endpoint.health.probes.add-additional-paths=true
```

then the `/actuator/health/{liveness,readiness}` endpoints are also exposed on the main port at `/{livez,readyz}`. N.B. this does not work if you also set `management.endpoint.health.group.*.show-details=always`.

## Startup Metrics

Auto-configuration exposes two metrics related to application startup:

* `application.started.time`: time taken to start the application.
* `application.ready.time`: time taken for the application to be ready to service requests.

You can also hook into the individual bean lifecycles and measure the startup perfrormance at a lower level with `ApplicationStartup`. Inject it into `SpringApplication` before you start it, or use a basic built-in implementation with `/actuator/startup`:

```java
public static void main(String[] args) {
    new SpringApplicationBuilder(MyApplication.class)
            .applicationStartup(new BufferingApplicationStartup(2048))
            .run(args);
}
```

NOTE: Watch out for the "Sring Boot Extension Pack" in VSCode - it drains the `/startup` endpoint on startup, so you never see any metrics in the endpoint. But you _do_ see them in code lenses above each `@Bean` or `@Configuration`.

## Info Endpoint

The `/info` endpoint is composed of `InfoContributors`. The original (Spring Boot 1.0) behaviour of rendering all `Environment` properties starting with `info.` is still there but you have to enable it explicitly now:

```
management.info.env.enabled=true
```

You also have to explicitly enable the endpoint itself (since Spring Boot 2.4):

```
management.endpoints.web.exposure.include=info
```

A new `InfoContributor` is the `JavaInfoContributor` which shows details of the runtime JDK:

```
$ curl localhost:8080/actuator/info | jq
```

result:

```json
{
  "dept": "mydepartment",
  "java": {
    "vendor": "Eclipse Adoptium",
    "version": "17.0.2",
    "runtime": {
      "name": "OpenJDK Runtime Environment",
      "version": "17.0.2+8"
    },
    "jvm": {
      "name": "OpenJDK 64-Bit Server VM",
      "vendor": "Eclipse Adoptium",
      "version": "17.0.2+8"
    }
  }
}
```

## Native Image

https://github.com/spring-projects-experimental/spring-native[Spring Native] can be used to convert a Spring Boot application into a native executable using https://github.com/oracle/graalvm[GraalVM]. Startup time is very fast and image sizes and memory usage also compare very favourably with the vanilla JVM for many applications. It worked with Spring Boot 2.5, but it tracks changes in Spring Framework and Spring Boot, so you need the latest versions for the best results. Spring Boot 2.6 provides several improvements that would be invisible to JVM users but manifest as more efficient memory usage and executable binary sizes.

Build:

```
$ mvn spring-boot:build-image
...
[INFO]     [creator]     Adding cache layer 'paketo-buildpacks/native-image:native-image'
[INFO] 
[INFO] Successfully built image 'docker.io/library/myproject:0.0.1-SNAPSHOT'
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  08:08 min
[INFO] Finished at: 2022-04-11T18:13:00+01:00
[INFO] ------------------------------------------------------------------------
```

and run:

```
$ docker run -p 8080:8080 myproject:0.0.1-SNAPSHOT
2022-04-12 05:35:20.069  INFO 1 --- [           main] o.s.nativex.NativeListener               : AOT mode enabled

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.6)

2022-04-12 05:35:20.070  INFO 1 --- [           main] com.example.myproject.MyApplication      : Starting MyApplication using Java 11.0.14.1 on 817f5d70b46e with PID 1 (/workspace/com.example.myproject.MyApplication started by cnb in /workspace)
2022-04-12 05:35:20.070  INFO 1 --- [           main] com.example.myproject.MyApplication      : No active profile set, falling back to 1 default profile: "default"
2022-04-12 05:35:20.096  WARN 1 --- [           main] i.m.c.i.binder.jvm.JvmGcMetrics          : GC notifications will not be available because MemoryPoolMXBeans are not provided by the JVM
2022-04-12 05:35:20.101  INFO 1 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 4 endpoint(s) beneath base path '/actuator'
2022-04-12 05:35:20.115  INFO 1 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port 8080
2022-04-12 05:35:20.116  INFO 1 --- [           main] com.example.myproject.MyApplication      : Started MyApplication in 0.055 seconds (JVM running for 0.059)
```

NOTE: https://start.spring.io[Spring Initializer] (and the tooling provided by IDEs that integrate with it) can generate a project template with the recommended settings for building a native image.

## Controller Endpoint Pattern Matcher

The default matcher for `@Controller` endpoints is now a regular expression matcher (with Spring Boot, but not with vanilla Spring Framework). You can go back to the old behaviour with a config flag `spring.mvc.pathmatch.matching-strategy=ant-path-matcher`. Watch out for the default being slightly stricter especially with Spring Security.

## Cookies Same Site Policy

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite[Same Site Policy] is now supported by all the web server platforms in Spring Boot, but only via server-specific APIs. Spring Boot abstracts those behind a shared `CookieSameSiteSupplier` and an enum `SameSite` (with values `STRICT`, `LAX`, `NONE`). You can change the global defaults with `server.servlet.session.cookie.same-site` (and the corresponding `reactive` property for WebFlux).

## Cycles

Bean cycles in an `ApplicationContext` can be resolved by Spring if one or both sides of the cycle has a property or field injection. It never works with constructor injection, which is a sign that it is a bad idea. Spring Boot fails fast in 2.6 and you have the option to refactor or set `server.servlet.session.cookie.same-site=true`.

## Records with `@ConfigurationProperties`

A `Record` with `@ConfigurationProperties` no longer requires `@ConstructorBinding` (the constructor is trivially the only way to create a `Record`). So you can replace this in Java 11:

```java
@ConfigurationProperties("greeting")
@ConstructorBinding
public class GreetingProperties {

    private String salutation;

    public  GreetingProperties(String salutation) {
        this.salutation = salutation;
    }

    public String salutation() {
        return salutation;
    }

}
```

with this in Java 17:

```java
@ConfigurationProperties("greeting")
public record GreetingProperties(String salutation) {
}
```

## Env Endpoint + Sanitizer

The `/env` endpoint has always supported individual fields being sanitized (e.g. based on their name). Now you can add a `SanitizingFunction` and control everything about the sanitization, including which fields are not shown at all.