:toc:

# What's New in Spring Boot 2.6

Demo code from the webinar "What's New in Spring Boot 2.6" with some commentary and extra detail on the main points.

Also see the https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes[Release Notes] and the https://github.com/spring-projects/spring-boot/milestones[release schedule] on Github.

## Health Endpoints on Main Port

When the actuator endpoints are configured on a different port (`management.server.port`) the health groups `/health/liveness` and `/health/readiness` can give misleading status unless they are switched to the main `server.port`. If you set

```
management.endpoint.health.probes.add-additional-paths=true
```

then the `/actuator/health/{liveness,readiness}` endpoints are also exposed on the main port at `/{livez,readyz}`. N.B. this does not work if you also set `management.endpoint.health.group.*.show-details=always`.

## Startup Metrics

Auto-configuration exposes two metrics related to application startup:

* `application.started.time`: time taken to start the application.
* `application.ready.time`: time taken for the application to be ready to service requests.

You can also hook into the individual bean lifecycles and measure the startup perfrormance at a lower level with `ApplicationStartup`. Inject it into `SpringApplication` before you start it, or use a basic built-in implementation with `/actuator/startup`:

```java
public static void main(String[] args) {
    new SpringApplicationBuilder(MyApplication.class)
            .applicationStartup(new BufferingApplicationStartup(2048))
            .run(args);
}
```

NOTE: Watch out for the "Sring Boot Extension Pack" in VSCode - it drains the `/startup` endpoint on startup, so you never see any metrics.

## Info Endpoint

The `/info` endpoint is composed of `InfoContributors`. The original (Spring Boot 1.0) behaviour of rendering all `Environment` properties starting with `info.` is still there but you have to enable it explicitly now:

```
management.info.env.enabled=true
```

You also have to explicitly enable the endpoint itself (since Spring Boot 2.4):

```
management.endpoints.web.exposure.include=info
```

A new `InfoContributor` is the `JavaInfoContributor` which shows details of the runtime JDK:

```
$ curl localhost:8080/actuator/info | jq
```

result:

```json
{
  "dept": "mydepartment",
  "java": {
    "vendor": "Eclipse Adoptium",
    "version": "17.0.2",
    "runtime": {
      "name": "OpenJDK Runtime Environment",
      "version": "17.0.2+8"
    },
    "jvm": {
      "name": "OpenJDK 64-Bit Server VM",
      "vendor": "Eclipse Adoptium",
      "version": "17.0.2+8"
    }
  }
}
```

## Native Image

https://github.com/spring-projects-experimental/spring-native[Spring Native] can be used to convert a Spring Boot application into a native executable using https://github.com/oracle/graalvm[GraalVM]. Startup time is very fast and image sizes and memory usage also compare very favourably with the vanilla JVM for many applications. It worked with Spring Boot 2.5, but it tracks changes in Spring Framework and Spring Boot, so you need the latest versions for the best results. Spring Boot 2.6 provides several improvements that would be invisible to JVM users but manifest as more efficient memory usage and executable binary sizes.

NOTE: https://start.spring.io[Spring Initializer] (and the tooling provided by IDEs that integrate with it) can generate a project template with the recommended settings for building a native image.

## Controller Endpoint Pattern Matcher

The default matcher for `@Controller` endpoints is now a regular expression matcher (with Spring Boot, but not with vanilla Spring Framework). You can go back to the old behaviour with a config flag `spring.mvc.pathmatch.matching-strategy=ant-path-matcher`. Watch out for the default being slightly stricter especially with Spring Security.

## Cookies Same Site Policy

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite[Same Site Policy] is now supported by all the web server platforms in Spring Boot, but only via server-specific APIs. Spring Boot abstracts those behind a shared `CookieSameSiteSupplier` and an enum `SameSite` (with values `STRICT`, `LAX`, `NONE`). You can change the global defaults with `server.servlet.session.cookie.same-site` (and the corresponding `reactive` property for WebFlux).

## Cycles

Bean cycles in an `ApplicationContext` can be resolved by Spring if one or both sides of the cycle has a property or field injection. It never works with constructor injection, which is a sign that it is a bad idea. Spring Boot fails fast in 2.6 and you have the option to refactor or set `server.servlet.session.cookie.same-site=true`.

## Records with `@ConfigurationProperties`

A `Record` with `@ConfigurationProperties` no longer requires `@ConstructorBinding` (the constructor is trivially the only way to create a `Record`).

## Env Endpoint + Sanitizer

The `/env` endpoint has always supported individual fields being sanitized (e.g. based on their name). Now you can add a `SanitizingFunction` and control everything about the sanitization, including which fields are not shown at all.